### ISSUE TITLE
Обучение в игре

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/RevolIT#22]
В самой игре при старте необходимо обучение, для снятия необходимости в объясняющем над ухом персоналом

**Comment by mentoster** [comment]
Нужно, чтобы не тратить время на выставке по объяснению как это работает

**Comment by CAPCHIK** [comment]
Стоит ли сделать что-то вроде сцены обучения? Где какой-то интерактивный ассистент будет рассказывать, что надо делать, тип мини челлендж выполнить как в обычных шутерах, когда учат кидать гранату, и так далее

Мне кажется это было бы интересно, можно даже записать анимации этой говорящей головы на mockup, и потом эту практику применить и в остальных проектах, что думает @RTUITLab/unity ?
