### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/RevolIT#23]
На данный момент игра выдает максимум 30 fps на мощном ПК, в то время как для полноценного VR необходимо 90 FPS

Предположительно проблема в использовании HDRP и текущих текстур

**Comment by Eloren1** [comment]
Если что, в Engine-VR тоже используется HDRP и очень тяжеловесные модели с текстурами, так проблема не в них. Скорее это связано с неоптимизированным освещением и кучей эффектов типо размытия, которые были изначально включены при создании проекта на основе шаблонного.

А что в итоге, @mentoster? А то название релиза «Optimization in more than 2» ни о чем не говорит)

**Comment by CAPCHIK** [comment]
Название было описано в слеке, в канале #revolit, просто не всегда эти выкладки попадают в issue

**Comment by mentoster** [comment]
> Если что, в Engine-VR тоже используется HDRP и очень тяжеловесные модели с текстурами, так проблема не в них. Скорее это связано с неоптимизированным освещением и кучей эффектов типо размытия, которые были изначально включены при создании проекта на основе шаблонного.
> 
> А что в итоге, @mentoster? А то название релиза «Optimization in more than 2» ни о чем не говорит)

Проблема не в моделях и не в эффектах, модели давно используют лоды (максимум 20к треугольников в камере), эффекты отключены
Проблема в огромном количестве высококачественных материалов и свете, с котором это всё должно обработаться
На один предмет приходится ~5 batches, а предметов там очень много (бутылки, картины, карты и т.д.) так еще и лоды на каждый из предметов
Были убраны горы и заменены на террейн, что сэкономило 100 batches, был оптимизирован collision culling, что позволило так же сократить batches
Опытом тыка был так же оптимизирован свет, что в 1.5 раза сократило вызовы отрисовки

До            |  После
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/50594730/147733155-f2960c97-e955-42c0-8f07-72ab64e23076.png) | ![image](https://user-images.githubusercontent.com/50594730/147733214-e97f50d2-ae26-4bee-abae-a313defda021.png)

**Comment by mentoster** [comment]
backed light делает наоборот хуже и количество вызовов отрисовки возрастаект

**Comment by mentoster** [comment]
Было переключено на URP - фпс стабилен и высок.
