### ISSUE TITLE
Перезапуск игры

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/RevolIT#24]
При завершении игры - смерти, необходимо создать корректный маршрут перезапуска для игрока

**Comment by mentoster** [comment]
Если остался один игрок, необходимо подождать (чтобы игроки поняли, что они уничтожили друг друга), затем выкинуть одного игрока, чтобы он создал сервер и присоединить остальных к нему
Сейчас при перезапуске, каждый игрок создает свой сервер (иногда нет, но главное исправить этот баг)

**Comment by mentoster** [comment]
Было бы еще здорово, если бы у победителя был текст с надписью: Вы победили!
