### ISSUE TITLE
Releases in readme

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/RevolIT#25]
В README описано, что нужно зайти в релизы, коих нет. Если README еще не готово, почему оно попало в master?

https://github.com/RTUITLab/RevolIT/blob/aac0e000b745b74aeed492303904cd8d6e58a7af/README.md?plain=1#L45-L51

**Comment by mentoster** [comment]
Задел на будущее), сейчас добавлю релиз, как только починю графику

**Comment by mentoster** [comment]
Добавлен релиз в репозиторий.
