### ISSUE TITLE
Подключение VR

### ISSUE THREAD

**Issue by leonis13579** [RTUITLab/RevolIT#3]
Подключение гарнитуры VR, а именно HTC VIVE PRO к Unity проекту.

Настройка сеттинга игры на небольшие передвижения с возможностью двигаться свободно по всем степеням свободы.

В качестве модели персонажа использовать куб закрепленным в области гарнитуры, а в качестве револьверов - сферы, закреплённые в зоне контроллеров.

**Comment by mentoster** [comment]
предлагаю вместо сфер доработать https://assetstore.unity.com/packages/templates/packs/revolver-kit-vr-no-code-needed-103118
