### ISSUE TITLE
В вр наблюдается желельный эффект

### ISSUE THREAD

**Issue by mentoster** [RTUITLab/RevolIT#31]
К сожалею записать баг не получается, в стим вр не отображается такое,
Но если надеть vive и быстро двигать рукой, все пространство вокруг руки двигается туда сюда
Я думаю это из-за  размытия, оно вроде уже отключено везде, но соровно как то проходит

**Comment by Delivery-Klad** [comment]
эта проблема от маленького количества кадров

**Comment by mentoster** [comment]
> эта проблема от маленького количества кадров

тогда закрываю issue
