### ISSUE TITLE
Передача информации попадания по противнику на жилет противника

### ISSUE THREAD

**Issue by leonis13579** [RTUITLab/RevolIT#8]
Необходимо реализовать отработку сетевого взаимодействия двух игроков на одной сцене с прохождение полного игрового сеттинга. 

При попадании одним игроком в другого должен передаться тактильный отклик на жилет раненного игрока.

С попаданием игрока по другому игроку кол-во его игровых очков должно увеличится. При критическом попадании или наборе определенного кол-ва некритических попаданий игрок должен получить информацию о своем проигрыше и отключиться от игры с получением итоговой суммы очков за раунд.

**Comment by CAPCHIK** [comment]
@mentoster верно понимаю, что это уже сделано, и можно закрыть данный issue?
