### ISSUE TITLE
Создание скриптов для интерактивного окружения 

### ISSUE THREAD

**Issue by mentoster** [RTUITLab/RevolIT#9]
- [ ] Добавление возможности перемещать предметы такие как стулья и бочки, разбивать окна, бутылки 
- [ ] Возможность взаимодействия с дверьми салуна, при их наличии 

Добавление этих скриптов на предметы должен быть простым

Этим займусь я, здесь таск, чтобы я не забыл это добавить

**Comment by Delivery-Klad** [comment]
игроки стоят на месте, поэтому перемещать предметы они не смогут, остается только бить бутылки

**Comment by leonis13579** [comment]
Здесь согласен с @Delivery-Klad, игроки могут максимум бить бутылки, но сделать это нужно.
Но делать это будем не в этой итерации.
